### PR TITLE
Close meta tags

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by fkorotkov** [comment]
Thank you! 🙌

**Comment by RDIL** [comment]
Thank you!  P.S. as a hardcore Cirrus fan, I am wondering how it is possible to maybe get an invite to the GH org?

**Comment by fkorotkov** [comment]
Hey @RDIL, at the moment we don't add external contributors since there are not that many of you. 😓 At some point I'll try to create several GitHub teams with separate permissions to allows having internal and external contributors. You'll be first on the list of external contributors. 😉 

BTW drop me an email to fedor@cirruslabs.org if you want me to send you some swag as a token of appreciation. 🙌

**Comment by RDIL** [comment]
Big sad 😓.  Alright, I'll drop you an email.  Hope teams come soon!

**Pull request merged**
