### PR TITLE
Fixed security issue in dep tree

### PR DESCRIPTION
**Pull request by RDIL**
Fixes a sub-dependencies' dependencies' dependencies' dependencies' dependencies' dependency being insecure

### CODE REVIEW

**Comment by fkorotkov** [comment]
How did you get `package-lock.json` updated? Which command did you run?

**Comment by RDIL** [comment]
`npm audit fix`

**Comment by fkorotkov** [comment]
Thank you!

**Comment by RDIL** [comment]
Also see #118

**Pull request merged**
