### PR TITLE
Optimizations (Attempt 2)

### PR DESCRIPTION
**Pull request by RDIL**
#138 but chips actually work

### CODE REVIEW

**Comment by RDIL** [comment]
@fkorotkov I swear it works now, I re-pinned MUI so the chips don't go crazy

**Comment by RDIL** [comment]
@fkorotkov first monday of 2020, maybe this will mean good luck?
Anyways, just tested it locally and found one bug - I fixed it.  This should be good to go.

**Comment by fkorotkov** [comment]
Happy 2020! I've started the year with upgrading all the things in #143. Will kindly ask you to rebase once #143 is merged (probably tomorrow).

**Comment by RDIL** [comment]
For some reason my devenv is now breaking - none of the commands work and I'm being forced to use yarn to install packages

**Comment by RDIL** [comment]
@fkorotkov we're good now!

**Comment by fkorotkov** [comment]
Did you run some linter or something like IntelliJ's inspections?

**Comment by RDIL** [comment]
Doing a final sweep of the code now.  I'll let you know if it has my green light in the morning.

**Comment by RDIL** [comment]
@fkorotkov I had to make some minor tweaks, but its all good now.

**Pull request merged**
