### PR TITLE
Improve styles, avoid crashing

### PR DESCRIPTION
**Pull request by RDIL**
[Privacy Badger](https://privacybadger.org/) successfully saved me (by preventing me from connecting to cloud.google.com), so I fixed this side effect of the request failing.  Also minor styling tweaks.

### CODE REVIEW

**Comment by fkorotkov** [comment]
@RDIL can you elaborate on the styling changes?

**Comment by RDIL** [comment]
> @RDIL can you elaborate on the styling changes?

It just makes the navbar items the exact same width apart.

**Comment by fkorotkov** [comment]
Thanks! But next time please create separate PRs and don't try to solve multiple problems in one. 👌

**Comment by RDIL** [comment]
Alright.

**Pull request merged**
