### PR TITLE
Show Task Resources

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/529

Screen Shot 2019-11-27 at 12 10 09 AM

/cc @eksperimental

### CODE REVIEW

**Comment by eksperimental** [comment]
The thing with this method is that the docker file is to long and it is trimed. Maybe use the title attribute

**Comment by fkorotkov** [comment]
This PR only adds resources. Image information was always there and sh uld probably use labels, yeah. But it's outside of the scope of this PR. 😅

**Comment by eksperimental** [comment]
I am not able to see the changes https://cirrus-ci.com/task/6362284892356608
Am i missing something?

**Comment by RDIL** [comment]
Nope, I can’t see them either

**Comment by RDIL** [comment]
@fkorotkov it doesn’t look like my PR was deployed either.  Any idea why it’s broken?

**Comment by fkorotkov** [comment]
Indeed, did a manual deploy of the latest. You might beed to hard refresh to get it. Thanks for noticing!

**Comment by eksperimental** [comment]
it works now! thank you

**Pull request merged**
