### PR TITLE
Hide the execution charts by default

### PR DESCRIPTION
**Pull request by RDIL**
When they are open like this, the page freezes for me.  The performance is much better (at least on my system) when this is hidden by default.  Plus, it adds a lot of visible bulk, and makes it almost like Travis CI where you have to do a bit of scrolling just to get to the logs, which isn't very great to have to deal with.  

(I also converted the related logic into a hook just for the purpose of cleaner code.)

Preview:

Signed-off-by: Reece Dunham <me@rdil.rocks>

### CODE REVIEW

**Comment by fkorotkov** [comment]
We need to solve a problem here that some people just always use 8 CPUs and those tasks are very underutilized. The usage charts help to highlight it if it's an issue. Probably we should show a utilization tips like "Max CPU Utilization was 82%" and have some kind of "Show details" which will show the charts. Also if utilization is under 50% then we should highlight it. I'll try to research how to better achieve this in UI. 🤔

**Comment by RDIL** [comment]
Understandable.  I think I can get this done pretty quickly.

**Comment by RDIL** [comment]
Here's an idea:
1. Make the TaskDetails paper a 2-tab layout, one being build information, and the other being build ***insights*** (implementation of fancy wording to tell people it is important)
2. We can use the Material-UI `badge` component to show a `1` on the build insights tab when something needs to be looked at (like an iPhone does)
3. We can put these charts on the insights tab

**Comment by RDIL** [comment]
@fkorotkov does this work until we can implement something like you described?

Screenshot 2020-05-28 at 2 43 02 PM

**Comment by fkorotkov** [comment]
I'm hesitant about hiding them by default since it doesn't freeze for me and I can scroll right away and in case of long logs you still need to scroll for quite a bit.

**Comment by RDIL** [comment]
I still do think its a bit of a bloat to just have it there, popping out on every single new build.  99% of the time I visit the site I just want logs, nothing else.

**Comment by fkorotkov** [comment]
IMO this is hiding too see for users who run 8 CPUs containers for a single core builds. I'll think of something like I've describe above. Probably with some expansion 🤔

**Pull request closed without merging**
