### PR TITLE
implement polling based auto refresh for TaskCommandList and TaskComm…

### PR DESCRIPTION
**Pull request by geekflyer**
…andLogs

This PR implements a temporary polling based workaround to get sense of "realtime" updates in the TaskCommandList and TaskCommandLogs view.
The polling logic can be removed once the websocket / subscription based updates work reliably.

Besides that this PR:
- Implements auto-expanding logs (when command is executing) similar to what was proposed by @RDIL in #87
- Fixes a small problem in DurationTicket which printed memory leak warnings / errors in the console due to uncleared `setTimeout` (also, using forceUpdate inside a .render function was kinda weird 😄 ).

### CODE REVIEW

**Comment by fkorotkov** [comment]
Seems like quite a lot of changes to be reverted in the end. What do you think of this temporary workaround on the Relay subscription level: #93?

**Comment by geekflyer** [comment]
@fkorotkov  I've update my PR a bit and split it into individual commits.
The first 3 commits are "permanent" fixes to problems not necesseraly related to the broken websocket subscrptions.
The 4th commit adds polling to *Details* pages in the network layer, based on your other PR (sorry I couldn't preserve your commit exactly, but it's more or less the same).
The 5th commit adds polling to the TaskCommandLogs (which is something your other PR didn't cover). Since TaskCommandLogs doesn't use the regular relay network layer and since the websocket subscription only sends `new logs` instead of the whole tail, this had to be implemented differently than the network layer enhancement for "Details" pages. Also note that the 5th commit also contains an enhancement on when TaskCommandLogs subscribes and unsubscribes to logs. It now makes sure that it only stays subscribed while the command is executing. The previous code could have resulted in keeping subscriptions for multiple commands alive, which is not a big deal with websockets, but is when using polling.

Once websocket based subscriptions properly work actually **only** the 4th commit and some part of the 5th commit have to be reverted (the 5th commit's subscribe/unsubscribe optimization can actually stay). Commit 1-3 should stay permanently.

Let me know what you think.

**Comment by geekflyer** [comment]
oh and just fyi, all the polling implementation (incl. the previous one in the network layer) is currently subject to potential out of order responses / race conditions when the network is slow. My first implementation of this PR took care of this but it made the code harder to read. Since this is hopefully just a temporary workaround I guess we can live with that for now.

**Comment by geekflyer** [comment]
@fkorotkov wdyt if I remove the last 2 commits (polling stuff) but we keep the first 3? I can rename the PR accordingly.

**Comment by fkorotkov** [comment]
now sure about `auto expand command logs when executing task`. do you really care for logs while it's executing? I personally prefer smaller instruction so I can overview the execution `clone -> cache -> install -> compile -> test -> artifacts -> ...`. What do you think?

**Comment by geekflyer** [comment]
I personally do, but I can understand your POV. In my cases the log outputs are usually also not crazy long so I still kinda get some overview. Maybe we can make this an optional button like / checkbox like "Follow logs" (similar to what some other CI systems do) and only when this is checked it expands the sections or so.

Also, would you mind checking out the branch it trying it out for yourself with a few buils? Maybe changes your mind :D

**Comment by fkorotkov** [comment]
Just tried it. I think auto-closing of sections might be a bit disturbing. UI is kind of shaking during that. 

When I personally need to follow log it's usually for a single command which I can manually expand even before it starts executing and logs will appear once it is executing.

I don't mind about "Follow logs" toggle but maybe without auto-closing... 🤔 What do you think?

**Comment by geekflyer** [comment]
okay, so you mean only auto expand, but no close right?
I guess one thing to avoid this shaking is also to really make sure the scroll position stays where focused on the last log line or something like that.
I will see if I can implement that.

**Comment by fkorotkov** [comment]
@geekflyer exactly! Another idea might be that with the this toogle on there will be only one log view similar to Travis one with ▷ kind of expansions:

Screen Shot 2019-08-02 at 4 47 18 PM

**Comment by geekflyer** [comment]
I was also thinking of maybe having a sidebar which shows the different command phases and their completion status and having a main container which follows the logs. That way we get a good combination of an high level overview and the ability to follow logs without shaking or losing the overview.

**Comment by fkorotkov** [comment]
Created #96 for ideas...

**Comment by geekflyer** [comment]
closing in favor of #97 and #96

**Pull request closed without merging**
