### PR TITLE
Avoid loading entire libraries to speed up development server

### PR DESCRIPTION
**Pull request by RDIL**
Makes the style the same throughout the repository.

### CODE REVIEW

**Comment by fkorotkov** [comment]
Do you really see performance improvement after the change? I though tree shaking is not happening for dev server and only happens for production builds to minimize the bundle size. 🤔

**Comment by fkorotkov** [comment]
Oh, the title missled me. It should be something like "Avoid loading whole modules to speed up dev server". I wonder if there is a way to have some linting around it.

**Comment by RDIL** [comment]
My bad.  Fixed now.

**Comment by fkorotkov** [comment]
Thanks! Doesn't look like it sped up startup time of the dev server for me.

**Comment by RDIL** [comment]
@fkorotkov its first time start when MUI hasn't been collected and cached yet by webpack/babel

**Comment by fkorotkov** [comment]
I tried to start the server multiple times before and after and all the times the time was around 25 seconds. 🤷

**Comment by RDIL** [comment]
No you need to delete `node_modules/.cache` I believe

**Pull request merged**
