### PR TITLE
Use babel-plugin-import

### PR DESCRIPTION
**Pull request by fkorotkov**
See discussion here: https://github.com/cirruslabs/cirrus-ci-web/pull/236

### CODE REVIEW

**Comment by fkorotkov** [comment]
@RDIL PTAL

**Comment by fkorotkov** [comment]
I don't think that works since I didn't install `babel-plugin-import`. i wonder why it didn't fail. 🤔

**Comment by RDIL** [comment]
@fkorotkov I believe that it doesn't respect the babelrc, which is why I was patching it in directly in.

**Comment by fkorotkov** [comment]
Seems we'll need this: https://github.com/ant-design/babel-plugin-import/issues/306

**Comment by RDIL** [comment]
Don't worry, I'm applying option 1 to all the code.

**Pull request closed without merging**
