### PR TITLE
Refactor reconnecting websocket code

### PR DESCRIPTION
**Pull request by RDIL**
Cleanup

### CODE REVIEW

**Comment by RDIL** [comment]
Hey @fkorotkov can you review this next time you get the chance - my fork is getting way too messy so I want to re-fork it but need to get this merged first :)

**Comment by fkorotkov** [comment]
Oh. What's the motivation for doing this refactoring? I don't see that upstream has changed since and usually `vendor` is updated only once there is an upstream change or there is a need in a monkey patch.

**Comment by RDIL** [comment]
This just makes the code more generally readable for everyone.  I was toying around with it when I opened this

**Comment by fkorotkov** [comment]
I'd say then it will be better to upstream the refactoring to https://github.com/joewalnes/reconnecting-websocket. In that situation if there will additional improvements upstream we won't need to deal with conflicts while cherry-picking.

**Pull request closed without merging**
