### PR TITLE
Changed typescript to use React JSX

### PR DESCRIPTION
**Pull request by RDIL**
Shouldn't have functional change, just nice to have

### CODE REVIEW

**Comment by fkorotkov** [comment]
Why is it nice to have?

**Comment by RDIL** [comment]
Forces IDEs like vscode to sync types with react jsx, instead of generic jsx

**Comment by fkorotkov** [comment]
Is there documentation around it? Would love to learn more about the specifics.

**Comment by RDIL** [comment]
https://www.typescriptlang.org/docs/handbook/jsx.html

**Pull request merged**
