### PR TITLE
Fix h1 content check

### PR DESCRIPTION
**Pull request by RDIL**
SEO report says the page is missing an h1 element
This should fix it

### CODE REVIEW

**Comment by fkorotkov** [comment]
Can you provide a link to the report? This change doesn't look right. Don't see a need to switch from higher order React Components.

**Comment by RDIL** [comment]
https://sitechecker.pro/seo-report/http://cirrus-ci.com - `H1-H6 check: H1 tag not found`

**Comment by fkorotkov** [comment]
There is an `h1` tag on the page

Screen Shot 2019-03-27 at 1 59 48 PM

**Comment by RDIL** [comment]
Strange.. it passes on my site

**Comment by fkorotkov** [comment]
Maybe it doesn't execute scripts which makes the reports so bad.

**Comment by RDIL** [comment]
I get the feeling that react has something to do with this

**Pull request closed without merging**
