### PR TITLE
Hooks: display environment variables used

### PR DESCRIPTION
**Pull request by edigaryev**
Looks like this:

Screenshot 2021-08-23 at 23 38 00

### CODE REVIEW

**Review by RDIL — CHANGES_REQUESTED** [review]
I feel like this would be better from a design perspective if it were a drawer that is closed by default.

**Review by fkorotkov — APPROVED** [review]
LGTM. IMO pretty consistent with the rest of the UI

**Comment by edigaryev** [comment]
> I feel like this would be better from a design perspective if it were a ~drawer~ (actually, expansion panel is what I meant) that is closed by default.

Note that currently we only display hook arguments, output and the environment on that page, nothing else. So it takes very little space.

Folding this information right now would just add useless clicks for the user, and we can always make all of them expandable later if needed.

**Comment by RDIL** [comment]
At the same time, information overload can be a problem.

**Pull request merged**
