### PR TITLE
Task debug information

### LINKED ISSUE #402: [question] How to control what package repository to use for FreeBSD?
It appears to use the quarterly repository by default, for example for [this .cirrus.yml](https://github.com/horizon-eda/horizon/blob/master/.cirrus.yml#L2).

I couldn't find in the documentation how to switch to the main (non-quarterly) repository.

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/402

### CODE REVIEW

**Comment by fkorotkov** [comment]
Here is an example of the events list. @edigaryev in which order do you think the events should be? I think descending is consistent with how commands are shown but still have some doubts.

Screen Shot 2021-11-26 at 10 57 21 AM

**Comment by edigaryev** [comment]
> I think descending is consistent with how commands are shown but still have some doubts.

Descending seems to be consistent with the commands logs output too, and this debug information looks like a log, so sticking to the descending order will in turn generate less surprises IMO.

**Comment by edigaryev** [comment]
I would, however, consider outputting the logs just as any other logs shown in the interface:

* it makes it easier to copy multiple lines and share them if anyone needs support
* there can be many lines of logs and scrolling is a must
* using monospaced font for technical details provides better readability (e.g. when distinguishing 0 (`0`) and O (`O`)

**Comment by fkorotkov** [comment]
The agent logs are actually now will be shown as the first command in the debug mode:

Screen Shot 2021-11-26 at 11 09 11 AM

**Pull request closed without merging**
